---
- name: Create user
  ansible.builtin.user:
    name: '{{ user_name }}'
    password: '{{ user_password }}'
    shell: /bin/bash
    groups: '{{ user_groups }}'

- name: Set authorized key
  ansible.posix.authorized_key:
    user: '{{ user_name }}'
    key: '{{ item }}'
    state: present
  loop: '{{ user_authorized_keys }}'

